Fix intermittent _WriteComputeLogsTo failure.
We sometimes see this error when writing Compute logs:
  UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 123412: ordinal not in range(128)

It doesn't happen very often (I've seen it twice in ~50 failure runs in the past few days), but it's very annoying because it results in an empty log file being uploaded.

Verified:
Fails:
```
logs = "some logs - " + u'\ufffd' + " -some more logs"
with open("/tmp/test.txt", 'w') as f:
  f.write(logs)
```

Succeeds:
```
logs = "some logs - " + u'\ufffd' + " -some more logs"
with open("/tmp/test.txt", 'w') as f:
  f.write(logs.encode("utf-8"))
```

Change-Id: I8e27dfc4501a39644a1f9b048b8e8c034fe9550e
Reviewed-on: https://chromium-review.googlesource.com/c/enterprise/cel/+/1521048
Reviewed-by: Fei Ling <feiling@chromium.org>