Retry setRuntimeConfigVariable on errNoSuchHost.
This is a very intermittent failure that has high impact.
Failing to set the runtime config variable means that cel_ctl will keep
seeing the asset as "in-progress", even if it's been failed, or worse, succeeded.

It will eventually timeout and fail (even if it should have succeeded!!!),
but only after ~1h. Some tests even set a bigger timeout (ad tree), which is worse.

Example:
In cel_agent:
```
remote_desktop.go:28: Remote Desktop Host config finished
deployer.go:403: Error updating config variable asset/windows_machine/win2012-client/status: Put https://runtimeconfig.googleapis.com/v1beta1/projects/celab-try-003/configs/cel-config/variables/asset/windows_machine/win2012-client/status?alt=json: dial tcp: lookup runtimeconfig.googleapis.com: no such host.
deployer.go:318: Everything is OK.
```

In cel_ctl:
```
watcher.go:68: 1 assets still deploying: map[ready:[...] in-progress:[windows_machine/win2012-client]]
logged_action.go:53: [ FAIL] WaitForAllAssetsReady: OnHost configuration timed out

  See instance console logs for more info:
  * https://console.cloud.google.com/compute/instances?project=celab-try-003
  WaitForAllAssetsReady
    OnHost configuration timed out
```

Change-Id: I468d35013c238f17cf23dc2a117773f2315ffcdd
Reviewed-on: https://chromium-review.googlesource.com/c/enterprise/cel/+/1541823
Reviewed-by: Fei Ling <feiling@chromium.org>