Improve PRESUBMIT.py RunGoTest error handling.
`go test -json -vet` can write error lines that are not JSON which makes our
presubmit function throw unfriendly errors.

Catch those and report them in a user-friendly way.


Before:
```
$ git cl upload
Running presubmit upload checks ...
Traceback (most recent call last):
  File "~/depot_tools/metrics.py", line 225, in print_notice_and_exit
    yield
  [git_cl.py stacktrace]
  File "~/depot_tools/presubmit_support.py", line 1547, in DoPresubmitChecks
    results += executer.ExecPresubmitScript(presubmit_script, filename)
  File "~/depot_tools/presubmit_support.py", line 1454, in ExecPresubmitScript
    result = eval(function_name + '(*__args)', context)
  File "<string>", line 1, in <module>
  File "<string>", line 106, in CheckChangeOnUpload
  File "<string>", line 97, in CommonChecks
  File "<string>", line 51, in RunGoTests
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```


After:
```
$ git cl upload
Running presubmit upload checks ...

** Presubmit Messages **
Missing OWNER reviewers for these files:
    PRESUBMIT.py

Suggested OWNERS: (Use "git-cl owners" to interactively select owners.)
    asanka@chromium.org is commented as:
      Owners for the Chrome Enterprise Lab project. (at <root>)

** Presubmit ERRORS **
Go tests failed
  FAIL  chromium.googlesource.com/enterprise/cel/go/common [build failed]

Go vet failed
  go/asset/deploy/windows_user.go:76: Errorf format %s has arg ch of [...] \
  go/common/walk_proto_test.go:105:45: too few values in &TestGoodProto [...] \
  go/gcp/operation.go:207: Errorf format %s has arg op.Error.Code of [...]

Presubmit checks took 1.9s to calculate.
```


Sample output with mixed build and assert failures:
```
** Presubmit ERRORS **
Go tests failed
  Test TestConfiguration_Merge_singleTextPb in [...]/enterprise/cel/go/cel \
  FAIL  chromium.googlesource.com/enterprise/cel/go/common [build failed]
```

Change-Id: I79f517f703ead5aa6bc240b447732dd9aad98a90
Reviewed-on: https://chromium-review.googlesource.com/c/1255558
Reviewed-by: Fei Ling <feiling@chromium.org>