Implement RunCommand (for tests) + MachineRegistryTest
^ Title.

Validated with:
> python ./test.py --test test.tests.MachineRegistryTest --host test.host.textpb
```
Running tests...

PASSED   VerifyRegistryKeys

1/1 tests passed.
```

Some examples of failures:
```
Running tests...

FAILED   VerifyRegistryKeys
Traceback (most recent call last):
  File "/test/infra/controller.py", line 70, in ExecuteTestCase
    test(self=testCaseInstance)
  File "/test/tests/machine_registry.py", line 21, in VerifyRegistryKeys
    'SomeMultiStringKey': '{First, Second, Third}'
  File "/test/tests/machine_registry.py", line 35, in assertRegistryContains
    self.assertEqual(ret, 0)
  File "/cel/test/infra/core/test_case.py", line 29, in assertEqual
    raise Exception("%s [first=%s, second=%s]" % (message, first, second))
Exception: Assertion failed [first=1, second=0]


0/1 tests passed.
```

```
  File "/test/tests/machine_registry.py", line 42, in assertRegistryContains
    self.assertTrue(key in actual, "Expected key (%s) missing from Get-ItemProperty output." % key)
  File "/test/infra/core/test_case.py", line 25, in assertTrue
    raise Exception(message)
Exception: Expected key (SomeNewStringKey) missing from Get-ItemProperty output.
```

```
[...]
  File "/test/tests/machine_registry.py", line 43, in assertRegistryContains
    self.assertEqual(actual[key], expected[key])
  File "/test/infra/core/test_case.py", line 29, in assertEqual
    raise Exception("%s [first=%s, second=%s]" % (message, first, second))

Exception: Assertion failed [first=123, second=999]
```
Change-Id: I5b74914fd726ada0ff4555e46b2a16139d137377
Reviewed-on: https://chromium-review.googlesource.com/c/1362170
Reviewed-by: Fei Ling <feiling@chromium.org>