Fix intermittent _RefreshAllLocks failure.
```
Traceback (most recent call last):
  File "/b/s/w/ir/cipd_bin_packages/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/b/s/w/ir/k/go/src/chromium.googlesource.com/enterprise/cel/test/infra/multi/shared_host_provider.py", line 240, in run
    self._provider._RefreshAllLocks()
  File "/b/s/w/ir/k/go/src/chromium.googlesource.com/enterprise/cel/test/infra/multi/shared_host_provider.py", line 191, in _RefreshAllLocks
    for host in self._lockedHosts:
RuntimeError: dictionary changed size during iteration
```

Fixed by iterating over a copy of the dictionary keys.
We already handle the case where we no longer own a lock we try to refresh.

Change-Id: I85bc873006ba2e91e51c4e50a651ef6fc0232878
Reviewed-on: https://chromium-review.googlesource.com/c/enterprise/cel/+/1521057
Reviewed-by: Fei Ling <feiling@chromium.org>