Basic E2E test for IISSites
Scope:
  Covers parsing/creating assets in cel_ctl.
  Covers deployment failures that result in the asset being marked bad.
    e.g. onhost script failures (exit_code != 0), or instances not booting.
  Doesn't cover testing environment functionality (coming later).


Usage:
  > ./test.py --test test.tests.IISSitesTest --host test.host.textpb
  > ./test.py --test test.tests.IISSitesTest --host test.host.textpb --nodeploy
  > ./test.py --test test.tests.IISSitesTest --host test.host.textpb --error_logs_dir=/tmp/logs/celab/


File layout:
  /test/infra
    - infra.core contains what test packages need to import to create test cases
    - infra.gcp contains all google API (compute & runtimeconfig) calls
    - controller.py contains high level test phases and validation
  /test/tests
    - depends on test.infra.core
    - contains test cases (1)


Requires googleapiclient.discovery:
  # TODO: Add to build.py deps --install
  > apt-get install python-pip
  > pip install google-api-python-client


Example success output:
```
Running tests...

PASSED   VerifyNTLMSite
PASSED   VerifyAnonymousSite

2/2 tests passed.
```

Example @environment failure output:
```
Waiting for all assets to be ready...
Traceback (most recent call last):
  File "test.py", line 79, in <module>
    c.DeployNewEnvironment(args.cel_ctl)
  File "test/infra/controller.py", line 59, in DeployNewEnvironment
    config.WaitForAllAssetsReady()
  File "test/infra/gcp/runtime_config.py", line 46, in WaitForAllAssetsReady
    raise AssetError('Deployment failed: %s' % assetStates['error'])
AssetError: Deployment failed: [u'windows_machine/domain2008-websites']

2018/11/29 03:13:08 test.py:90: [ERROR] Test failed.
```

Example @test failure output:
```
Running tests...

FAILED   VerifyNTLMSite
Traceback (most recent call last):
  File "test/infra/controller.py", line 81, in ExecuteTestCase
    test(self=testCaseInstance)
  File "test/tests/iis_sites.py", line 22, in VerifyNTLMSite
    self.SomeOtherMethod()
  File "test/tests/iis_sites.py", line 26, in SomeOtherMethod
    raise Exception("This is an exception!")
Exception: This is an exception!

PASSED   VerifyAnonymousSite

1/2 tests passed.

```

Change-Id: I37662b90c83deba5c62e1d49ba97097fcf431b34
Reviewed-on: https://chromium-review.googlesource.com/c/1355344
Reviewed-by: Fei Ling <feiling@chromium.org>