Fix LUCI celab tests on Windows.
Added the .exe to the cel_ctl path.

Also bumped the oauth vpython wheel to a newer version because that version had a threading bug on Windows:
> File "C:\b\s\w\ir\cache\vpython\4b9d64\lib\site-packages\oauth2client\contrib\locked_file.py", line 165, in unlock_and_close
>     os.unlink(lock_filename)
> WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\b\\s\\w\\ir\\tmp\\t\\google-api-python-client-discovery-doc.cache.lock'

Windows test run:
https://ci.chromium.org/swarming/task/4538e2f444ad4410

Change-Id: Ic54b621fb036a57950f2b72436f3b63ec49fae23
Reviewed-on: https://chromium-review.googlesource.com/c/enterprise/cel/+/1642366
Reviewed-by: Fei Ling <feiling@chromium.org>